name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      builds-dir:
        description: ビルドするファイルを選択
        required: true
        type: choice
        options:
          - terraform-kubectl

env:
  BUILD_DIR:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set Build Dir
        run: |
          BUILD_DIR="./containers/${{ inputs.builds-dir }}"
          echo "Build directory: ${BUILD_DIR}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        working-directory: ${{env.BUILD_DIR}}
        run: |
          docker build -t container .